services:
  - type: web
    name: thread-cart-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        value: 207594028823-5kc0j2nt6la0ni6jv56i30jqbrikn3rb.apps.googleusercontent.com
      - key: VITE_API_BASE_URL
        value: https://your-backend-domain.vercel.app/api